version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
test: off  
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/nareshpatel/api/v2/package
  api_key:
    secure: vNnR3JtJ56EgixJy8xExDC/x0t3W06V8W3lenbbGQRjzOKgnVCPWFKZtHqJdLatE
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: fnlclMsUQvEvqaFBv8UlYUvitXLKQsK/+nIYabyqaHPJBa1K+ebcFkXa8ADq4mdH
  on:
    branch: master
    appveyor_repo_tag: true